[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "rococo-local"

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1000
chain = "asset-hub-rococo-local"
cumulus_based = true

    [[parachains.collators]]
    name = "assethub-collator01"
    ws_port = 9910
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace", "--state-cache-size=0" ]

    [[parachains.collators]]
    name = "assethub-collator02"
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace", "--state-cache-size=0"]

[[parachains]]
id = 3369
chain = "local-v"
cumulus_based = true

    [[parachains.collators]]
    name = "muse-collator01"
    ws_port = 9920
    command = "./target/release/mythos-node"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

    [[parachains.collators]]
    name = "muse-collator02"
    command = "./target/release/mythos-node"
    args = ["-lxcm=trace", "--state-cache-size=0"]

