[relaychain]
default_command = "./bin/polkadot"
default_args = ["-lparachain=debug", "-lxcm=trace"]
chain = "paseo-local"
chain_spec_command = "./bin/paseo-chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

    [[relaychain.nodes]]
    name = "alice"
    rpc_port = 9900
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1000
chain = "asset-hub-paseo-local"
chain_spec_command = "./bin/paseo-chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

    [[parachains.collators]]
    name = "assethub-collator01"
    rpc_port = 9910
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace", "--trie-cache-size=0"]

    [[parachains.collators]]
    name = "assethub-collator02"
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace", "--trie-cache-size=0"]

[[parachains]]
id = 3369
chain = "local-v"
cumulus_based = true

    [[parachains.collators]]
    name = "muse-collator01"
    rpc_port = 9920
    command = "./target/release/mythos-node"
    args = ["-lxcm=trace", "--trie-cache-size=0"]

    [[parachains.collators]]
    name = "muse-collator02"
    command = "./target/release/mythos-node"
    args = ["-lxcm=trace", "--trie-cache-size=0"]
