name: Zombienet TPS

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: TPS zombienet
    runs-on: parity-large
    container:
        image: docker.io/paritytech/ci-unified:bullseye-1.84.1-2025-01-28-v202502131220
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Node
        run: cargo build --profile=production --all

      - name: Save parachain binary
        run: |
          mkdir -p bins
          cp target/production/mythos-node bins/mythos-node

      - name: Polkadot binaries
        run: |
          mkdir -p bins
          cd bins
          LINKS=$(curl  -H 'Accept: application/vnd.github+json' https://api.github.com/repos/paritytech/polkadot-sdk/releases |jq -r -c  '[ .[] |select(.target_commitish="polkadot-stable2503") |.assets | .[] | select(.name == "polkadot" or .name == "polkadot-prepare-worker" or .name == "polkadot-execute-worker")| .browser_download_url] | .[0,1,2]')
          for link in $(echo $LINKS);do
            echo "downloading $link"
            curl -L -O $link
          done;
          chmod +x polkadot*
          cd ..

      - name: Run Zombienet
        run: |
          export PATH=$(pwd)/bins:$PATH
          export ZOMBIE_SPECS=$(pwd)/zombienet-sdk-tests/tps/chainspec
          cargo run --manifest-path zombienet-sdk-tests/tps/Cargo.toml
