# Test storage migration using try-runtime on PRs with label "migration"
name: Test storage migration

on:
  pull_request:
    types: [labeled, synchronize]
  push:
    branches: [ main ]

jobs:
  try_runtime:
    if: contains(github.event.pull_request.labels.*.name, 'migration')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup worker
        uses: "./.github/templates/setup-worker"

      - name: Cache Build artefacts
        uses: actions/cache/restore@v3
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ env.POLKA_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-release-${{ env.POLKA_VERSION }}

      - name: Install try-runtime
        run: |
          echo "---------- Downloading try-runtime CLI ----------"
          curl -sL https://github.com/paritytech/try-runtime-cli/releases/download/v0.4.0/try-runtime-x86_64-unknown-linux-musl -o try-runtime
          chmod +x ./try-runtime

      - run: |
          echo "Found label runtime_migration. Running tests"
          echo "---------- Running try-runtime for Muse ----------"
          cargo build --locked --release --features try-runtime && \
          ./try-runtime --runtime ./target/release/wbuild/mythos-testnet/target/wasm32-unknown-unknown/release/testnet_runtime.wasm \
              on-runtime-upgrade --checks pre-and-post --disable-idempotency-checks live --uri wss://paseo-muse-rpc.polkadot.io:443
        env:
          RUST_LOG: remote-ext=debug,runtime=debug
